"""empty message

Revision ID: 24428fd84ff4
Revises: 9c511800a346
Create Date: 2019-02-13 11:51:09.900418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24428fd84ff4'
down_revision = '9c511800a346'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_delete', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('token', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'token')
    op.drop_column('user', 'is_delete')
    # ### end Alembic commands ###
