"""empty message

Revision ID: b291fd7a1cb2
Revises: 759a68cc94ae
Create Date: 2019-01-24 11:45:51.885202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b291fd7a1cb2'
down_revision = '759a68cc94ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('job', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('sex', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'sex')
    op.drop_column('user', 'job')
    # ### end Alembic commands ###
