"""empty message

Revision ID: e02f90d10cb8
Revises: 9b22d3d976b8
Create Date: 2019-01-24 20:56:28.185064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e02f90d10cb8'
down_revision = '9b22d3d976b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('companyName', sa.String(length=20), nullable=True),
    sa.Column('companyType', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'user', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'company_id')
    op.drop_table('company')
    # ### end Alembic commands ###
